#!/bin/bash
v4l2-ctl \
--set-ctrl=brightness=128 \
--set-ctrl=contrast=140 \
--set-ctrl=saturation=120 \
--set-ctrl=white_balance_temperature_auto=1 \
--set-ctrl=gain=10 \
--set-ctrl=power_line_frequency=2 \
--set-ctrl=white_balance_temperature=4321 \
--set-ctrl=sharpness=145 \
--set-ctrl=backlight_compensation=1 \
--set-ctrl=exposure_auto=1 \
--set-ctrl=exposure_absolute=150 \
--set-ctrl=exposure_auto_priority=1 \
--set-ctrl=focus_auto=1 \
--set-ctrl=zoom_absolute=0
