#!/bin/sh

#============================================================
# ~/bin/start_plex
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Stop servers
#------------------------------------------------------------
echo "-----Kill Roon Server-----"
echo "Killing Roon"
sleep 1s
sudo systemctl stop roonbridge.service
sudo systemctl stop roonserver.service
echo "Done...Roon Inactive"

#------------------------------------------------------------
# Verify status
#------------------------------------------------------------
echo "Verifying Roon Bridge status"
sudo systemctl status roonbridge.service
while true; do
    read -p "Do you wish to continue?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
sleep 1s
echo "Verifying Roon Server status"
sudo systemctl status roonserver.service
while true; do
    read -p "Do you wish to continue?" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

#------------------------------------------------------------
# Unmount Metadata
#------------------------------------------------------------
echo "Unmounting Roon Metadata"
sudo umount /var/roon/RoonServer
sleep 3s
echo "Done"
echo "Metadata Unmounted"

#------------------------------------------------------------
# Unmount Devices
#------------------------------------------------------------
echo "Unmounting Devices"
sudo umount /media/pabloa/SG8TI
sleep 1s
echo "Done..."

# Set vim filetype
# vim: set ft=sh:
