#!/bin/sh

#============================================================
# ~/bin/start_plex
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Stop servers
#------------------------------------------------------------
echo "-----Kill Plex Services-----"
echo "Killing Plex"
sleep 1s
sudo systemctl stop plexmediaserver.service
echo "Done...Plex Inactive"

# Set vim filetype
# vim: set ft=sh:
