#!/bin/sh

#============================================================
# ~/bin/rofi_powermenu
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Open rofi power menu
#------------------------------------------------------------
# Options to be displayed
option0=" Lock"
option1=" Logout"
option2=" Suspend"
option3=" Scheduled suspend (10min)"
option4=" Scheduled suspend (20min)"
option5=" Scheduled suspend (30min)"
option6=" Reboot"
option7=" Shutdown"

# Options passed into variable
options="$option0\n$option1\n$option2\n$option3\n$option4\n$option5\n$option6\n$option7"

# Note: -i will disable case sensitivity (will toggle)
chosen="$(echo -e "$options" | rofi -theme ~/.config/rofi/themes/general_thick.rasi -lines 8 -dmenu -p "Power" -i)"
case $chosen in
    $option0)
        /home/pabloagnck/bin/start_scripts/start_lockscreen;;
    $option1)
        bspc quit;;
    $option2)
        systemctl suspend;;
	$option3)
		sleep 600 && systemctl suspend;;
	$option4)
		sleep 1200 && systemctl suspend;;
	$option5)
		sleep 1800 && systemctl suspend;;
    $option6)
        systemctl reboot;;
    $option7)
        systemctl poweroff;;
esac

# Set vim filetype
# vim: set ft=sh:
