#!/bin/sh

#============================================================
# ~/bin/start_plex
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Unmount WD, and remount by UUID on /media/pabloagnck/WD
#------------------------------------------------------------
echo "-----Init Music Server-----"
echo "Unmounting devices..."
umount /run/media/pabloa/WD8TI
sleep 1s
umount /run/media/pabloa/SG8TI
sleep 1s

echo "Mounting devices..."
sudo mount -U 917e5a5f-caeb-429b-889a-e218ad4579d4 /media/pabloagnck/WD8TI
sleep 1s
sudo mount -U 8cfa6b57-3ca8-4e55-baae-e6cf6f65d54d /media/pabloagnck/SG8TI
sleep 1s

#------------------------------------------------------------
# Mount Metadata & Media
#------------------------------------------------------------
echo "Mounting Roon Metadata..."
sudo mount --bind /media/pabloagnck/SG8TI/Metadata/RoonServer /var/roon/RoonServer
sleep 3s

echo "Mounting Plex Metadata..."
sudo mount --bind /media/pabloagnck/SG8TI/Metadata/Plex\ Media\ Server /var/lib/plex/Plex\ Media\ Server
sleep 3s

#------------------------------------------------------------
# Init plex server
#------------------------------------------------------------
echo "Initializing Plex Server..."
sleep 1s
sudo systemctl start plexmediaserver.service

echo "Initializing Roon Server..."
sleep 1s

sudo systemctl start roonserver.service
echo "Roon Server Online"
sleep 1s

echo "Initializing Roon Bridge..."
echo "Roon Bridge Online"
sudo systemctl start roonbridge.service

echo "Have Fun"

# Set vim filetype
# vim: set ft=sh:
