#!/bin/sh

#============================================================
# ~/bin/start_netflix
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Open netflix on new firefox window
#------------------------------------------------------------
$BROWSERB -new-window 'https://www.netflix.com/'

# Set vim filetype
# vim: set ft=sh:
