#!/bin/sh

#============================================================
# ~/bin/start_roon
# Pablo Aguirre Núñez
#============================================================

echo "-----Init Roon Services-----"
echo "Unmounting devices..."

#------------------------------------------------------------
# Init plex server
#------------------------------------------------------------
echo "Initializing Roon Server"
sleep 2s
sudo systemctl start roonserver.service
echo "Roon Server Online"
sleep 1s
echo "Initializing Roon Bridge"
sudo systemctl start roonbridge.service

echo "Have fun..."

# Set vim filetype
# vim: set ft=sh:
