#!/bin/sh

#============================================================
# ~/bin/start_youtube
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Open youtube on new firefox window
#------------------------------------------------------------
firefox -new-window 'https://www.youtube.com/'

# Set vim filetype
# vim: set ft=sh:
