#!/bin/sh

#============================================================
# ~/bin/utils_torrent_add
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Start transmission-cli (daemon), and add torrent. (For use with xdg-open)
#------------------------------------------------------------

# Transmission-daemon sometimes fails to take remote requests in its first moments.
# Init transmission daemon (transmission-cli) before adding torrent.
pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Started Transmission Daemon" && sleep 3)

# Add torrent to transmission-cli. -a = add, $@ = current file as variable.
transmission-remote -a "$@" && notify-send "Transmission Daemon" "Torrent Added"
