#!/bin/sh

# I. Get movie IDs and output to text file
for filename in /run/media/pabloagnck/WD8TI/Media/Music_II/Album/*
do
  artist=$filename
  song="$(ls "$artist"/*)"
  echo $artist $song  >> /home/pabloagnck/Documents/songs1.txt
done;
