#!/bin/sh

#============================================================
# ~/bin/utils_colors256
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Display colorpalette with 256 colors.
# From 0 to 16: cterm colors
#------------------------------------------------------------
for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done

# Set vim filetype
# vim: set ft=sh:
