#!/bin/sh

#============================================================
# ~/bin/utils_takescreenshot
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Take new screenshot. Full screen or selection based.
#------------------------------------------------------------
DIR="${HOME}/pictures/screenshots"
DATE="$(date +%Y-%m-%d--%H-%M-%S)"
NAME="${DIR}/screenshot-${DATE}.png"
LOG="${DIR}/screenshots.log"

# Screenshot the entire screen
if [ "$1" = "scr" ];
  then
    import -format png -window root "${NAME}";
    notify-send "Full Screen" -t 2000;
fi

# Screenshot a selected area
if [ "$1" = "area" ];
  then
    import -format png "${NAME}";
    notify-send "Selected Screen" -t 2000;
fi

if [[ $# = 0 ]]; then
    # Display a warning if no area defined
    echo "No screenshot area has been specified. Screenshot not taken."
    echo "${DATE}: No screenshot area has been defined. Screenshot not taken." >> "${LOG}"
else
    # Save the screenshot in the directory and edit the log
    echo "${NAME}" >> "${LOG}"
fi

# Set vim filetype
# vim: set ft=sh:
