#!/bin/sh

#============================================================
# ~/bin/wakeup-events-something
# Pablo Aguirre Núñez
#============================================================

#------------------------------------------------------------
# Disable wakeup events.
#------------------------------------------------------------
echo RP01 > /proc/acpi/wakeup
echo RP02 > /proc/acpi/wakeup
echo RP03 > /proc/acpi/wakeup
echo ARPT > /proc/acpi/wakeup
echo RP05 > /proc/acpi/wakeup
echo RP06 > /proc/acpi/wakeup
echo XHC1 > /proc/acpi/wakeup

# Set vim filetype
# vim: set ft=sh:
